name: Run R script

on:
  schedule:
    # Run once a day at 00:00
    - cron: '0 0 * * *'
  workflow_dispatch:
  
jobs:
  run-script:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Set up pandoc
        uses: r-lib/actions/setup-pandoc@v2

      - name: Restore R packages cache
        uses: actions/cache@v2
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-r-${{ hashFiles('**/DESCRIPTION') }}
          restore-keys: ${{ runner.os }}-r-

      - name: Run R script
        run: Rscript dothis.R
        
      - name: Commit results
        run: |
          git add -A
          git commit -m 'New AQ data. Maps updated!' || echo "No changes"
          git push origin || echo "No changes to commit"        
